services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fastapi_amazon_q_dev:${FASTAPI_AMAZON_Q_DEV_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      FASTAPI_AMAZON_Q_DEV_HOST: 0.0.0.0
      FASTAPI_AMAZON_Q_DEV_DB_FILE: /db_data/db.sqlite3
    volumes:
      - fastapi_amazon_q_dev-db-data:/db_data/



volumes:
  fastapi_amazon_q_dev-db-data:
    name: fastapi_amazon_q_dev-db-data
